AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
  TargetRubyVersion: 2.2

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 119
  IgnoreCopDirectives: true

Metrics/AbcSize:
  Max: 16.5

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'