version: 2
jobs:
  build:
    working_directory: ~/egg
    docker:
      - image: ruby:2.4.0
    steps:
      - run:
          name: build-deps
          command: |
            apt-get -qq update
            apt-get install -qqy cmake
      - checkout
      - type: cache-restore
        key: egg-bundler-{{ checksum "Gemfile.lock" }}
      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - type: cache-save
        key: egg-bundler-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run:
          name: rspec
          command: |
            mkdir -p "/tmp/test-results"
            export TEST_FILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 \
                              -r rspec_junit_formatter \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              ${TEST_FILES}
      - type: store_test_results
        path: /tmp/test-results