version: 2
jobs:
  build:
    working_directory: ~/leash
    docker:
      - image: ruby:2.4.0
    steps:
      - run:
          name: build-deps
          command: |
            apt-get -qq update
            apt-get install -qqy cmake
      - checkout
      - type: cache-restore
        key: leash-bundler-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - type: cache-save
        key: leash-bundler-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run:
          name: rspec
          command: |
            mkdir -p /tmp/test-results
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests)
      - type: store_test_results
        path: /tmp/test-results