#! /usr/bin/env ruby

require "fileutils"

FileUtils.mkpath(%w(vendor bundle))

# 'or fail $?' is an idiom. system calls set $? to the Process Status, so we will raise an exception to that tune.
system "eval $(aws --profile smokey ecr get-login)" or fail "#{$?}"

# Speed up build by pulling from amazon.
system "docker-compose pull" or fail "#{$?}"
system "docker-compose build" or fail "#{$?}"

FileUtils.cp ".env.template", ".env"

system "docker-compose up -d"
print "App is now running at http://localhost:3000"
